server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
### springcloud gateway配置
  cloud:
    gateway:
      # 开关
      enabled: true
      #配置路由规则
      routes:
        - id: api-member
          uri: lb://app-mayikt-member
          predicates:
            - Path=/api-member/**
          filters:
            - StripPrefix=1
        - id: api-order
          uri: lb://app-mayikt-order
          predicates:
            - Path=/api-order/**
          filters:
            - StripPrefix=1
      #discovery:
        #locator:
        #开启自动路由,以服务id建立路由，服务id默认大写
        #enabled: true
        #lower-case-service-id: true
###eureak注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


### 配置网关反向代理 最新版的springcloud不支持了
#zuul:
#  routes:
#    api-a:
#      ### 以 /api-member/访问转发到会员服务
#      path: /api-member/**
#      serviceId: app-mayikt-member
#    api-b:
#      ### 以 /api-order/访问转发到订单服务
#      path: /api-order/**
#      serviceId: app-mayikt-order

