# 应用服务 WEB 访问端口
server:
  port: 9010
# 应用名称
spring:
  application:
    name: mayikt-sentinel
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    nacos:
      discovery:
        # Nacos认证信息
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
    # Sentinel Dashboard 控制台
    sentinel:
      # 取消Sentinel控制台懒加载
      # 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
      # 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
      eager: true
      # Sentinel 控制台地址
      transport:
        dashboard: localhost:8718
        # 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
        #client-ip:
