# 应用服务 WEB 访问端口
server:
  port: 80
# 应用名称
spring:
  application:
    name: mayikt-gateway
  cloud:
    gateway:
      discovery:
        #开启以服务id去注册中心上获取转发地址
        locator:
          enabled: true
      #配置路由规则
      routes:
        - id: mayikt
          uri: http://www.mayikt.com/
          filters:
            - StripPrefix=1
          predicates:
            - Path=/mayikt/**
        - id: member
          #基于lb负载均衡形式转发
          uri: lb://mayikt-member
          filters:
            - StripPrefix=1
          predicates:
            - Path=/member/**
        - id: order
          #基于lb负载均衡形式转发
          uri: lb://mayikt-order
          filters:
            - StripPrefix=1
          predicates:
            - Path=/order/**
        #路由谓词工厂：https://cloud.spring.io/spring-cloud-gateway/reference/html/#gateway-request-predicates-factories
        #1.匹配时间 After Before Between
#        - id: my_after_route
#          uri: http://www.mayikt.com/
#          predicates:
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2022-01-21T17:42:47.789-07:00[America/Denver]
        #2.匹配对应的host
#        - id: my_host_route
#          uri: https://www.bilibili.com/
#          predicates:
#            - Host=mybilibili.cn
        #3.权重控制
#        - id: weight_bilibili_high
#          uri: https://www.bilibili.com/
#          predicates:
#            - Weight=group1, 8
#        - id: weight_mayikt_low
#          uri: http://www.mayikt.com/
#          predicates:
#            - Weight=group1, 2
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    nacos:
      discovery:
        # Nacos认证信息
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/mayikt_gateway?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.mayikt.entity
  configuration:
    map-underscore-to-camel-case: true
