# 应用服务 WEB 访问端口
server:
  port: 80
# 应用名称
spring:
  application:
    name: mayikt-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
      #配置路由规则
      routes:
        - id: mayikt
          uri: http://www.mayikt.com/
          predicates:
            - Path=/mayikt/**
        - id: member
          #基于lb负载均衡形式转发
          uri: lb://mayikt-member
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: order
          #基于lb负载均衡形式转发
          uri: lb://mayikt-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    nacos:
      discovery:
        # Nacos认证信息
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/meite_gateWay?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

