# 服务器端口号
server:
  port: 8010
# dubbo 注册中心名称
dubbo:
  application:
    name: order
  # 采用dubbo协议，指定发布端口号
  protocol:
    name: dubbo
    port: 20880
  # dubbo 注册中心地址
  registry:
    address: zookeeper://localhost:2181
  # 调用服务超时时间
  consumer:
    timeout: 5000