server:
  port: 8888
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/joeljhou/sc-config.git
          ####搜索目录
          search-paths:
            - project_config
      ####读取分支
      label: master

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka